version: '3'

services:
  frontend:
    build:
      context: ./Frontend
    ports:
      - "8080:8080"

  backend:
    build:
      context: ./Backend
    ports:
      - "3000:3000"
    depends_on:
      - frontend